### ISSUE TITLE
Import error for scm_processed_message_decode

### ISSUE THREAD

**Issue by Indigi-managed** [jcu-eresearch/SCM_Utils#1]
Hey Nigel, Justin here, seems to be an issue with the latest push:

from scm.utils.scm_msg import scm_processed_message_decode
ImportError: cannot import name 'scm_processed_message_decode' from 'scm.utils.scm_msg' - scm_msg.py

**Comment by nigelb** [comment]
Hi Justin,

The problem was an import of the old checksum file not in the repo:

```python
>>> from scm.utils.scm_msg import scm_processed_message_decode
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/nigelb/.python/3/scm_test/lib/python3.8/site-packages/scm/utils/scm_msg.py", line 41, in <module>
    from scm.kineis.checksums_kineis import BCH32
ModuleNotFoundError: No module named 'scm.kineis.checksums_kineis'
```

Should be fixed now.

**Comment by Indigi-managed** [comment]
Yep that fixed it thanks
